# Generated by Django 4.2 on 2023-04-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_inmate_jurisdictionurl_searchurl_inmatebookingnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmate',
            name='book_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
