# Generated by Django 4.2 on 2023-05-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_inmate_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmate',
            name='booking_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inmate',
            name='release_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
