# Generated by Django 4.2 on 2023-05-14 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_inmate_booking_date_alter_inmate_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='products.inmatebookingnumber'),
        ),
    ]
