# Generated by Django 4.2 on 2023-01-30 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_charge_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SexOffender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.charge')),
                ('inmate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.inmate')),
            ],
        ),
    ]
