# Generated by Django 4.2 on 2023-05-24 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_sexoffender_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sexoffender',
            name='inmate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.inmate', unique=True),
        ),
    ]
