# Generated by Django 4.2 on 2023-05-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_sexoffender_inmate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sexoffender',
            name='charges',
        ),
        migrations.AddField(
            model_name='inmate',
            name='is_sex_offender',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
