# Generated by Django 4.2 on 2023-06-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_sexoffender_charges_inmate_is_sex_offender'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmate',
            name='is_in_custody',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
