# Generated by Django 4.2 on 2023-06-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_delete_sexoffender'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmate',
            name='was_added_when',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
